spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_sms?serverTimezone=Asia/Shanghai&useUnicode=true&charaterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver